CREATE DATABASE IF NOT EXISTS Nota;

CREATE TABLE IF NOT EXISTS `Nota`.`Users` ( 
    `id` VARCHAR(36) NOT NULL PRIMARY KEY , 
    `username` VARCHAR(50) NOT NULL UNIQUE, 
    `password` VARCHAR(255) NOT NULL, 
    `fullname` VARCHAR(50) NOT NULL,
    `email` VARCHAR(50) NOT NULL UNIQUE, 
    `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `Nota`.`Notes` ( 
    `id` VARCHAR(36) NOT NULL PRIMARY KEY, 
    `title` TEXT,
    `text` TEXT, 
    `image` TEXT,
    `public` BOOLEAN DEFAULT FALSE,
    `author` VARCHAR(255) NOT NULL,
    `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`author`) REFERENCES Users(`username`)
);

CREATE TABLE IF NOT EXISTS `Nota`. `UserNotes`(
    `userID` VARCHAR(36) NOT NULL,
    `NoteID` VARCHAR(36) NOT NULL,
    `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`userID`) REFERENCES Users(`id`), 
    FOREIGN KEY (`NoteID`) REFERENCES Notes(`id`),
    UNIQUE (userID, NoteID)
);