CREATE DATABASE IF NOT EXISTS Nota;

CREATE TABLE IF NOT EXISTS `Nota`.`Users` ( 
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY , 
    `username` VARCHAR(255) NOT NULL UNIQUE, 
    `password` VARCHAR(255) NOT NULL, 
    `fullname` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE, 
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
